<?xml version='1.0'?>

<robot name="bot" 
  xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="robotname" value="bot"/>
  <xacro:property name="set_gazebo_plugins" value="1"/>

  <xacro:macro name="default_origin">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:macro>

<!-- BASE_LINK PARAMETERS -->
  <xacro:property name="bot_mass" value="25.0"/>
  <xacro:property name="bot_width" value="0.2"/>
  <xacro:property name="bot_length" value="0.35"/>
  <xacro:property name="bot_height" value="0.1"/>
  <xacro:macro name="base_geometry">
    <geometry>
      <box size="${bot_length} ${bot_width} ${bot_height}"/>
    </geometry>
  </xacro:macro>
  
  <xacro:macro name="default_inertia">
    <inertia ixx="0.6" ixy="0" ixz="0" iyy="0.65" iyz="0" izz="0.21"/>
  </xacro:macro>
<!-- BASE_FOOTPRINT PARAMETERS -->
  <xacro:property name ="base_footprint_size" value="0.01"/>
<!-- BALL PARAMETERS -->
  <xacro:property name="ball_radius" value="0.05"/>
  <xacro:property name="ball_mass" value="0.3"/>
  <xacro:macro name="ball_inertia">
   <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
  </xacro:macro>

<!-- WHEEL PARAMETERS -->
  <xacro:property name="wheel_mass" value="2"/>
  <xacro:property name="wheel_radius" value="${ball_radius}"/>
  <xacro:property name="wheel_thickness" value="0.02"/>
  <xacro:property name="wheel_base_length_coefficient" value="${1/3}"/>

  <xacro:macro name="wheel_geometry">
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}"/>
  </xacro:macro>

  <xacro:macro name="wheel_inertia">
    <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
  </xacro:macro>

  <xacro:macro name="wheel" params="name *origin_wheel">
    <joint name="${name}_wheel_joint" type="continuous">
      <axis xyz="0 1 0" rpy="0 0 0" />
      <parent link="base_link"/>
      <child link="${name}_wheel"/>
      <xacro:insert_block name="origin_wheel"/>
    </joint>

    <link name="${name}_wheel">
      <visual>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
        <xacro:wheel_geometry/>
      </visual>
      <collision>
        <xacro:wheel_geometry/>
      </collision>
      <inertial>
        <xacro:wheel_geometry/>
        <mass value="${wheel_mass}"/>
        <xacro:wheel_inertia/>
      </inertial>
    </link>
      <!-- GAZEBO settings for wheels -->
    <gazebo reference="${name}_wheel">
      <mu1>1000000.0</mu1>
      <mu2>1000000.0</mu2>
      <minDepth>0.0001 </minDepth>
      <fdir1 value = "1 0 0"/>
      <kp>100000.0</kp>
      <kd>100000 </kd>
      <material>Gazebo/Black</material>
    </gazebo>
  </xacro:macro>


<!-- DEFINITIONS OF ROBOT -->
  <!-- BASE LINK -->
  <link name='base_link'>
    <pose>0 0 0 0 0 0</pose>

    <inertial>
      <mass value="${bot_mass}"/>
      <xacro:default_inertia/>
    </inertial>

    <collision name='collision'>
      <xacro:default_origin/>
      <xacro:base_geometry/>
    </collision>

    <visual name='visual'>
       <xacro:default_origin/>
       <xacro:base_geometry/>
    </visual>
  </link>
  <!-- BASE_FOOTPRINT -->
  <link name='base_footprint'>
    <collision name="base_footprint_collision">
      <xacro:default_origin/>
      <geometry>
        <sphere radius="${base_footprint_size}"/>
      </geometry>
    </collision>
    <visual name="ball_visual">
      <xacro:default_origin/>
      <geometry>
        <sphere radius="${base_footprint_size}"/>
      </geometry>
    </visual>
    <inertial>
      <mass value="0.001"/>
      <xacro:default_origin/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>
  
  <joint type="fixed" name="base_ftprnt__base_link_joint">
    <origin xyz="${bot_length*wheel_base_length_coefficient} 0 ${-bot_height/2}" rpy="0 0 0"/>
    <child link="base_footprint"/>
    <parent link="base_link"/>
    <axis xyz="0 0 0" rpy="0 0 0"/>
  </joint>
 
  <!-- CASTER BALL -->

  <link name="ball">
    <collision name="ball_collision">
      <xacro:default_origin/>
      <geometry>
        <sphere radius="${ball_radius}"/>
      </geometry>
    </collision>
    <visual name="ball_visual">
      <xacro:default_origin/>
      <geometry>
        <sphere radius="${ball_radius}"/>
      </geometry>
    </visual>
    <inertial>
      <mass value="${ball_mass}"/>
      <xacro:default_origin/>
      <xacro:ball_inertia/>
    </inertial>
  </link>


  <joint type="fixed" name="ball_joint">
    <origin xyz="${-bot_length*4/10} 0 ${-bot_height/2}" rpy="0 0 0"/>
    <child link="ball"/>
    <parent link="base_link"/>
    <axis xyz="0 0 0" rpy="0 0 0"/>
    
  </joint>

  <!-- WHEELS -->
  
  <xacro:wheel name="right">
    <origin xyz="${bot_length*wheel_base_length_coefficient} ${-bot_width/2} ${-bot_height/2}" rpy="0 0 0"/>
  </xacro:wheel>

  <xacro:wheel name="left">
    <origin xyz="${bot_length*wheel_base_length_coefficient} ${bot_width/2} ${-bot_height/2}" rpy="0 0 0"/>
  </xacro:wheel>

  <!-- LIDAR -->

  <joint name="lidar_joint" type="fixed">
    <axis xyz="0 0 0" />
    <origin xyz="${bot_length*6/7} 0 ${bot_height}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="lidar"/>
  </joint>

  <link name="lidar">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.03 0.03"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.03 0.03"/>      
      </geometry>
    </visual>
    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
  <!-- GAZEBO PLUGINS -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <alwaysOn>true</alwaysOn>
      <publishTf>1</publishTf>
      <updateRate>50</updateRate>
      <leftJoint>left_wheel_joint</leftJoint>
      <rightJoint>right_wheel_joint</rightJoint>
      <wheelSeparation>0.2</wheelSeparation>
      <wheelDiameter>0.05</wheelDiameter>
      <torque>75</torque>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>base_link</robotBaseFrame>
      <odometrySource>world</odometrySource>
      <publishWheelTF>true</publishWheelTF>
      <publishWheelJointState>true</publishWheelJointState>
    </plugin>
  </gazebo>

  <gazebo reference="ball">
    <kp>1000000.0</kp>
    <kd>10000</kd>
    <dampingFactor>0.0</dampingFactor>
    <mu1>0.00</mu1>
    <mu2>0.00</mu2>
    <fdir1 value = "1 0 0"/>
    <maxVel>15.0</maxVel>
    <material>Gazebo/Red</material>
  </gazebo> 

  <gazebo reference="lidar">
    <sensor type="ray" name="head_hokuyo_sensor_front">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>40</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-1.3</min_angle>
            <max_angle>1.3</max_angle>
            <!-- 1.570796 -->
          </horizontal>
        </scan>
        <range>
          <min>0.1</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <!-- Noise parameters based on published spec for Hokuyo laser
               achieving "+-30mm" accuracy at range < 10m.  A mean of 0.0m and
               stddev of 0.01m will put 99.7% of samples within 0.03m of the true
               reading. -->
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
        <topicName>scan</topicName>
        <frameName>lidar</frameName>
      </plugin>
    </sensor>
  </gazebo>
</robot>