TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.5
  min_vel_x: 0

  max_vel_theta:  1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.1

  acc_lim_x: 2.0
  acc_lim_y: 2.0
  acc_lim_theta: 3.2

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.1

# Differential-drive robot configuration
  holonomic_robot: false

# Forward Simulation Parameters
  sim_time: 1.7
  sim_granularity: 0.025
  vx_samples: 5
  vtheta_samples: 15

  escape_vel: -0.2
