obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[-0.5, -0.25], [-0.5, 0.25], [0.5, 0.25], [0.5, -0.25]]
footprint_padding: 0.05

inflation_radius: 1.0
cost_scaling_factor: 1.2

map_type: costmap
observation_sources: scan
scan: {sensor_frame: lidar, data_type: LaserScan, topic: scan, marking: true, clearing: true}
