DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.07
  min_vel_x: -0.07

  max_vel_y: 0  
  min_vel_y: 0

# The velocity when robot is moving in a straight line
  max_trans_vel:  0.07
  min_trans_vel:  -0.07

  max_rot_vel: 0.7
  min_rot_vel: -0.7

  acc_lim_x: 0.5
  acc_lim_y: 0
  acc_lim_theta: 0.7

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.3
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 1.3
  vx_samples: 10 #значение пониженно, так как увеличение вызывает missed control loops
  vy_samples: 0
  vth_samples: 40
  controller_frequency: 4.32

# Trajectory Scoring Parameters
  path_distance_bias: 32
  goal_distance_bias: 20
  occdist_scale: 0.09
  forward_point_distance: 0.2 #пониженно чтобы робот меньше крутился при достижении цели
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.09

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
