global_costmap:
  global_frame: map
  robot_base_frame: base_footprint #центр base_footprint находится прямо между колес
                                  #именно это пофиксило вращение робота при достижении цели 


  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.6 #maximum amount of latency allowed between these transforms
  static_map: false
  rolling_window: true
  width: 20.0
  height: 20.0
 
